---
title: 'GEOG 6960 Causality in Geographic Studies'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author:
  - Simon Brewer^[University of Utah, simon.brewer@ess.utah.edu]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: false
    toc: false
    toc_float: false
---

# Introduction

Often in scientific studies we are interested in establishing a cause and effect, e.g. what is the effect of some policy on health outcomes or the effect of anthropogenic activity on a changing climate. However, most statistical texts and courses are taught using correlative methods, with the mantra that “correlation is not causation” outside of certain strict experimental conditions. Recent work by Judea Pearl and others have developed a framework (Structural Causal Modeling) for causal inference that allows causality to be inferred even when these conditions are not met, allowing this approach in a much broader range of studies. In this seminar, we will review the history and concepts of causal analysis, and go through the steps of Pearl’s causal framework using a set of hands-on examples. The class will largely follow the outline of The Book of Why (Pearl and Mackenzie, 2018; Basic Books, NY). Students will develop their own analysis over the course of the semester through a series of discussions and presentations.

# Classes

- Week 1
- Week 2
    - [Lab notes][lab2]
- Week 3
    - [Lab notes][lab3]
- Week 5
    - [Lab notes][lab5]
- Week 6
    - [Lab notes][lab6]
- Week 7
    - [Lab notes][lab7]
- Week 8
    - [Lab notes][lab8]
- Week 9
    - [Lab notes][lab9]
- Week 10
    - [Lab notes][lab10]
- Week 11
    - [Lab notes][lab11]

# Data

- Grace and Keely dataset ([keeley.csv][keeley])
- Mosquito net dataset ([mosquito_nets.csv][mosquito])
- Shipley tree mortality dataset ([shipley.csv][shipley])
- Boreal NDVI dataset ([boreal.csv][boreal])
- Travis and Grace data set ([travis.csv][travis])
- Travel survey data ([survey.txt][survey])
- Week 11 example 1  ([week11_ex1.csv][wk11_1])
- Week 11 example 3  ([week11_ex4.csv][wk11_3])
- Week 11 example 4  ([week11_ex5.csv][wk11_4])

[lab2]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week2.html
[lab3]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week3.html
[lab5]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week5.html
[lab6]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week6.html
[lab7]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week7.html
[lab8]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week8.html
[lab9]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week9.html
[lab10]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week10.html
[lab11]: https://simonbrewer.github.io/geog6960_causal/GEOG6960_Week11.html

[keeley]: https://drive.google.com/file/d/1_pOumBe6a783Jap4oyQlF0uJ_IwmjqpZ/view?usp=drive_link
[mosquito]: https://drive.google.com/file/d/1TbscKcYSuDhOg_FPhb5faIPyNGuNdTUA/view?usp=sharing
[shipley]: https://drive.google.com/file/d/14MNcR3IT2GsVvHAb1P2r5gZAmiIjoomZ/view?usp=sharing
[boreal]: https://drive.google.com/file/d/1Kl_nqCETZyg92RL2lVdtGaWcfSDcXE_x/view?usp=sharing
[travis]: https://drive.google.com/file/d/1CG__WvPOvS_5yUfAoNE4ovD7u77sH_rq/view?usp=sharing
[survey]: https://drive.google.com/file/d/1odUn9ofSnjnde46rNAUA7kT2DJRyGTyz/view?usp=sharing
[wk11_1]: https://drive.google.com/file/d/1QVHGP-JLc0BDdrqqhKe3AT_Y4qfkh3Ce/view?usp=sharing
[wk11_3]: https://drive.google.com/file/d/19IE2XiJ2wwAH9la3YPlh2llWu-Gs6Zar/view?usp=sharing
[wk11_4]: https://drive.google.com/file/d/1DLxuAJgvnG0PcQwqD-nDD_JLiH7kT75B/view?usp=sharing